# Generated by Django 3.2.6 on 2021-08-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'permissions': (('puede_validar', 'Puede validar'),), 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
    ]
